// <auto-generated />
using System;
using GolfMatchPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfMatchPro.Data.Migrations
{
    [DbContext(typeof(GolfMatchDbContext))]
    [Migration("20260416172321_AddMatchNameToMatch")]
    partial class AddMatchNameToMatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GolfMatchPro.Data.Entities.BetConfiguration", b =>
                {
                    b.Property<int>("BetConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BetConfigId"));

                    b.Property<bool>("AutoPressEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CompetitionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DunnAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("DunnEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("ExpenseDeductionPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("HandicapPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("InvestmentOffAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("InvestmentOffEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxNetScore")
                        .HasColumnType("int");

                    b.Property<decimal>("Nassau18")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("NassauBack")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("NassauFront")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PressAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PressDownThreshold")
                        .HasColumnType("int");

                    b.Property<decimal>("RedemptionAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("RedemptionEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("ScoresCountingPerHole")
                        .HasColumnType("int");

                    b.Property<decimal?>("SkinsBuyIn")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("SkinsPerSkinAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TotalStrokesBetPerStroke")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("BetConfigId");

                    b.HasIndex("MatchId");

                    b.ToTable("BetConfigurations");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.BetResult", b =>
                {
                    b.Property<int>("BetResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BetResultId"));

                    b.Property<int>("BetConfigId")
                        .HasColumnType("int");

                    b.Property<decimal>("InvestmentResult")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Nassau18Result")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("NassauBackResult")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("NassauFrontResult")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PressResult")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ResultDetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SkinsAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SkinsWon")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalStrokesResult")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WinLossAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("BetResultId");

                    b.HasIndex("BetConfigId");

                    b.HasIndex("PlayerId");

                    b.ToTable("BetResults");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<decimal>("CourseRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SlopeRating")
                        .HasColumnType("int");

                    b.Property<string>("TeeColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YearOfInfo")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.CourseHole", b =>
                {
                    b.Property<int>("CourseHoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseHoleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("HandicapRanking")
                        .HasColumnType("int");

                    b.Property<int>("HoleNumber")
                        .HasColumnType("int");

                    b.Property<int>("Par")
                        .HasColumnType("int");

                    b.HasKey("CourseHoleId");

                    b.HasIndex("CourseId", "HoleNumber")
                        .IsUnique();

                    b.ToTable("CourseHoles", t =>
                        {
                            t.HasCheckConstraint("CK_CourseHole_HandicapRanking", "[HandicapRanking] >= 1 AND [HandicapRanking] <= 18");

                            t.HasCheckConstraint("CK_CourseHole_HoleNumber", "[HoleNumber] >= 1 AND [HoleNumber] <= 18");

                            t.HasCheckConstraint("CK_CourseHole_Par", "[Par] >= 3 AND [Par] <= 6");
                        });
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.GrandTotal", b =>
                {
                    b.Property<int>("GrandTotalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrandTotalId"));

                    b.Property<string>("DetailJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludeBestBall")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeFivesomes")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeFoursomes")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeIndividual")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeIndoTourney")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeRoundRobins")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeSkinsGross")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeSkinsNet")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeThreesomes")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalWinLoss")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("GrandTotalId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("GrandTotals");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByPlayerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("MatchDate")
                        .HasColumnType("date");

                    b.Property<string>("MatchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MatchId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedByPlayerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.MatchScore", b =>
                {
                    b.Property<int>("MatchScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchScoreId"));

                    b.Property<int>("CourseHandicap")
                        .HasColumnType("int");

                    b.Property<int>("GrossTotal")
                        .HasColumnType("int");

                    b.Property<int>("Hole1")
                        .HasColumnType("int");

                    b.Property<int>("Hole10")
                        .HasColumnType("int");

                    b.Property<int>("Hole11")
                        .HasColumnType("int");

                    b.Property<int>("Hole12")
                        .HasColumnType("int");

                    b.Property<int>("Hole13")
                        .HasColumnType("int");

                    b.Property<int>("Hole14")
                        .HasColumnType("int");

                    b.Property<int>("Hole15")
                        .HasColumnType("int");

                    b.Property<int>("Hole16")
                        .HasColumnType("int");

                    b.Property<int>("Hole17")
                        .HasColumnType("int");

                    b.Property<int>("Hole18")
                        .HasColumnType("int");

                    b.Property<int>("Hole2")
                        .HasColumnType("int");

                    b.Property<int>("Hole3")
                        .HasColumnType("int");

                    b.Property<int>("Hole4")
                        .HasColumnType("int");

                    b.Property<int>("Hole5")
                        .HasColumnType("int");

                    b.Property<int>("Hole6")
                        .HasColumnType("int");

                    b.Property<int>("Hole7")
                        .HasColumnType("int");

                    b.Property<int>("Hole8")
                        .HasColumnType("int");

                    b.Property<int>("Hole9")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("NetTotal")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ReportableScore")
                        .HasColumnType("int");

                    b.HasKey("MatchScoreId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("MatchScores");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("EntraUserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("HandicapIndex")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.RoundRobinResult", b =>
                {
                    b.Property<int>("RoundRobinResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoundRobinResultId"));

                    b.Property<int>("BetConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaderboardJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("MatchupsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoundRobinType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RoundRobinResultId");

                    b.HasIndex("BetConfigId");

                    b.HasIndex("MatchId", "BetConfigId", "RoundRobinType");

                    b.ToTable("RoundRobinResults");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int>("BetConfigId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("BetConfigId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.TeamPlayer", b =>
                {
                    b.Property<int>("TeamPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamPlayerId"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("TeamPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("TeamPlayers");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.BetConfiguration", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.Match", "Match")
                        .WithMany("Bets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.BetResult", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.BetConfiguration", "BetConfiguration")
                        .WithMany("Results")
                        .HasForeignKey("BetConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfMatchPro.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BetConfiguration");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.CourseHole", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.Course", "Course")
                        .WithMany("Holes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.GrandTotal", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfMatchPro.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Match", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfMatchPro.Data.Entities.Player", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.MatchScore", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.Match", "Match")
                        .WithMany("Scores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfMatchPro.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.RoundRobinResult", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.BetConfiguration", "BetConfiguration")
                        .WithMany()
                        .HasForeignKey("BetConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfMatchPro.Data.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BetConfiguration");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Team", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.BetConfiguration", "BetConfiguration")
                        .WithMany("Teams")
                        .HasForeignKey("BetConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BetConfiguration");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.TeamPlayer", b =>
                {
                    b.HasOne("GolfMatchPro.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GolfMatchPro.Data.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.BetConfiguration", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Course", b =>
                {
                    b.Navigation("Holes");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Match", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("GolfMatchPro.Data.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
